[firebase]
apiKey = "AIzaSyBxxeZC-EyZJOOsbmYl-tOo_jdReqtlr-s"
authDomain = "redevelopment-calculator.firebaseapp.com"
databaseURL = "https://redevelopment-calculator-default-rtdb.firebaseio.com"
projectId = "redevelopment-calculator"
storageBucket = "redevelopment-calculator.firebasestorage.app"
messagingSenderId = "835598182612"
appId = "1:835598182612:web:a6a2c380e5f34fec18b341"
